### ISSUE TITLE
Can't find Pretrained model in the repo

### ISSUE THREAD

**Issue by farazBhatti** [subeeshvasu/2018_subeesh_epsr_eccvw#2]

**Comment by subeeshvasu** [comment]
Hi,

I didn't understand your comment!. Can you please elaborate on what you meant?

**Comment by subeeshvasu** [comment]
You can get the pretrained models via the link provided here - https://github.com/subeeshvasu/2018_subeesh_epsr_eccvw/tree/master/EPSR_testcode

Are you not able to access them?
