### ISSUE TITLE
PyTorch migration

### ISSUE THREAD

**Issue by shazib-summar** [subeeshvasu/2018_subeesh_epsr_eccvw#5]
Hi, is there any possibility of migrating the project to PyTorch 1.3 or above? PyTorch 0.4 is seriously deprecated...

**Comment by subeeshvasu** [comment]
Hi, I am no longer working on this project. Feel free to make changes and make a PR. It should be easy to migrate to Pytorch 1.3. Also, do we really need to make any changes to the test codes I provided here to reproduce the same results via Pytorch 1.3?

**Comment by shazib-summar** [comment]
Thanks for the quick reply.

> do we really need to make any changes to the test codes

Yes, a lot of classes, for instance _DataLoaderIter, have been rendered obsolete

**Comment by subeeshvasu** [comment]
Cool. I won't be able to find time for this migration anytime soon. But in case if you would like to have a try, please go ahead and then please make a PR. :)
