### ISSUE TITLE
Configuring the dataset directories for training the model

### ISSUE THREAD

**Issue by shazib-summar** [subeeshvasu/2018_subeesh_epsr_eccvw#6]
I, for the love of God, cannot figure out how to configure the DIV2K dataset directory in order to train the model. I have a folder named `div2k` inside the data directory and inside the `div2k` folder are the folder `DIV2K_train_HR` and `DIV2k_valid_HR`.

However when I run the training loop, I get the error `data.div2k has no attribute DIV2K_train_HR`.

Please help me by providing the correct configuration details.

**Comment by subeeshvasu** [comment]
Are u using the training code of EDSR guys? (If yes, then have a look at - https://github.com/thstkdgus35/EDSR-PyTorch/issues/103) I do remember having the same error when I tried their code for the first time, but then I might have made some changes to get it run, I just don't remember. Let me know which code you are running? and also the line number and filename that throws this error.

**Comment by shazib-summar** [comment]
I'll look into it

**Comment by shazib-summar** [comment]
Im using your code. The line is [this](https://github.com/subeeshvasu/2018_subeesh_epsr_eccvw/blob/118b38de5282215ca075baa88446561a4d7fd4cc/EPSR_testcode/code/data/__init__.py#L19) one. I tried it on Colab as well. I've tried the issue in the link that you provided, but nothing helpful.
```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    loader = data.Data(args)
  File "/content/2018_subeesh_epsr_eccvw/EPSR_testcode/code/data/__init__.py", line 19, in __init__
    trainset = getattr(module_train, args.data_train)(args)
AttributeError: module 'data.div2k' has no attribute 'DIV2K'
```

**Comment by subeeshvasu** [comment]
Are you not familiar with Python? My code is not for training, it's only for testing. If you are planning to run training, you should use all the code snippets from EDSR, which has this missing module namely "DIV2K".

**Comment by shazib-summar** [comment]
Yes, you're right. Thank you for your help.
